#include <catch2/catch_test_macros.hpp>

#include <array>

#include <kmx/sat/cdcl/bank/watch_list.hpp>
#include <kmx/sat/cdcl/clause/database.hpp>
#include <kmx/sat/cdcl/variable_mapper.hpp>
#include <kmx/sat/cdcl/watch.hpp>
#include <kmx/sat/literal.hpp>
#include <kmx/sat/proof_manager.hpp>
#include <kmx/sat/simplify/engine/congruence.hpp>
#include <kmx/sat/simplify/engine/decomposition.hpp>
#include <kmx/sat/simplify/engine/instantiation.hpp>
#include <kmx/sat/simplify/engine/probing.hpp>
#include <kmx/sat/simplify/engine/sweep.hpp>
#include <kmx/sat/simplify/equivalence_substitutor.hpp>
#include <kmx/sat/simplify/transitive_reducer.hpp>

namespace kmx::sat::simplify
{

    TEST_CASE("engine simplify", "[sat]")
    {
        using namespace kmx::sat;
        using namespace kmx::sat::simplify;

        equivalence_substitutor decomposition_substitutor;
        engine::decomposition decomposition;
        decomposition.attach_substitutor(decomposition_substitutor);
        REQUIRE(decomposition.has_substitutor());
        decomposition.add_implication(1u, 2u);
        decomposition.add_implication(2u, 1u);
        decomposition.add_implication(3u, 4u);
        decomposition.add_implication(4u, 3u);
        decomposition.add_implication(2u, 3u);
        REQUIRE(decomposition.unique_implication_edge_count() == 5u);
        REQUIRE(decomposition.implication_attempt_count() == 5u);
        REQUIRE(decomposition.rejected_zero_implication_count() == 0u);
        REQUIRE(decomposition.accepted_implication_count() == 5u);
        REQUIRE(decomposition.edge_density_per_node_per_mille() == 1250u);
        REQUIRE(decomposition.average_outgoing_implication_per_node_floor() == 1u);
        REQUIRE(decomposition.outgoing_implication_count(1u) == 1u);
        REQUIRE(decomposition.outgoing_implication_count(2u) == 2u);
        REQUIRE(decomposition.outgoing_implication_count(9u) == 0u);
        REQUIRE(decomposition.has_implication(2u, 3u));
        REQUIRE_FALSE(decomposition.has_implication(3u, 2u));
        const auto baseline_graph_snapshot = decomposition.graph_metrics_snapshot();
        REQUIRE(baseline_graph_snapshot.node_count == 4u);
        REQUIRE(baseline_graph_snapshot.unique_implication_edge_count == 5u);
        REQUIRE(baseline_graph_snapshot.implication_attempt_count == 5u);
        REQUIRE(baseline_graph_snapshot.rejected_zero_implication_count == 0u);
        REQUIRE(baseline_graph_snapshot.accepted_implication_count == 5u);
        REQUIRE(baseline_graph_snapshot.dropped_duplicate_edge_count == 0u);
        REQUIRE(baseline_graph_snapshot.average_outgoing_implication_per_node_floor == 1u);
        REQUIRE(baseline_graph_snapshot.edge_density_per_node_per_mille == 1250u);
        REQUIRE(baseline_graph_snapshot.has_substitutor);
        const auto baseline_reset_snapshot = decomposition.reset_metrics_snapshot();
        REQUIRE(baseline_reset_snapshot.reset_graph_invocation_count == 0u);
        REQUIRE(baseline_reset_snapshot.reset_run_invocation_count == 0u);
        REQUIRE(baseline_reset_snapshot.reset_emit_invocation_count == 0u);
        REQUIRE(baseline_reset_snapshot.reset_telemetry_invocation_count == 0u);
        REQUIRE(baseline_reset_snapshot.clear_graph_invocation_count == 0u);
        REQUIRE(baseline_reset_snapshot.total_reset_invocation_count == 0u);
        const auto baseline_consistency_before_runs = decomposition.consistency_metrics_snapshot();
        REQUIRE(baseline_consistency_before_runs.implication_accounting_consistent);
        REQUIRE(baseline_consistency_before_runs.component_accounting_consistent);
        REQUIRE(baseline_consistency_before_runs.substitution_accounting_consistent);
        REQUIRE(baseline_consistency_before_runs.emit_accounting_consistent);
        REQUIRE(baseline_consistency_before_runs.reset_accounting_consistent);
        REQUIRE(baseline_consistency_before_runs.overall_consistent);
        REQUIRE(decomposition.telemetry_consistent());
        decomposition.run_scc();
        REQUIRE(decomposition.scc_run_count() == 1u);
        REQUIRE(decomposition.tarjan_visit_count() == 4u);
        REQUIRE(decomposition.max_tarjan_stack_depth() == 4u);
        REQUIRE(decomposition.successor_scan_count() == 5u);
        REQUIRE(decomposition.tree_edge_relaxation_count() == 3u);
        REQUIRE(decomposition.back_edge_relaxation_count() == 2u);
        REQUIRE(decomposition.root_component_extraction_count() == 2u);
        REQUIRE(decomposition.canonicalized_successor_list_count() == 4u);
        REQUIRE(decomposition.canonicalized_successor_edge_count() == 5u);
        REQUIRE(decomposition.scc_empty_run_count() == 0u);
        REQUIRE(decomposition.average_component_size_floor() == 2u);
        const auto baseline_scc_snapshot = decomposition.scc_metrics_snapshot();
        REQUIRE(baseline_scc_snapshot.scc_run_count == 1u);
        REQUIRE(baseline_scc_snapshot.scc_empty_run_count == 0u);
        REQUIRE(baseline_scc_snapshot.component_count == 2u);
        REQUIRE(baseline_scc_snapshot.singleton_component_count == 0u);
        REQUIRE(baseline_scc_snapshot.non_singleton_component_count == 2u);
        REQUIRE(baseline_scc_snapshot.max_component_size == 2u);
        REQUIRE(baseline_scc_snapshot.average_component_size_floor == 2u);
        REQUIRE(baseline_scc_snapshot.tarjan_visit_count == 4u);
        REQUIRE(baseline_scc_snapshot.max_tarjan_stack_depth == 4u);
        REQUIRE(baseline_scc_snapshot.successor_scan_count == 5u);
        REQUIRE(baseline_scc_snapshot.tree_edge_relaxation_count == 3u);
        REQUIRE(baseline_scc_snapshot.back_edge_relaxation_count == 2u);
        REQUIRE(baseline_scc_snapshot.root_component_extraction_count == 2u);
        REQUIRE(baseline_scc_snapshot.canonicalized_successor_list_count == 4u);
        REQUIRE(baseline_scc_snapshot.canonicalized_successor_edge_count == 5u);
        REQUIRE(baseline_scc_snapshot.successor_scans_per_unique_edge_per_mille == 1000u);
        decomposition.find_equivalences();
        REQUIRE(decomposition.find_equivalence_run_count() == 1u);
        REQUIRE(decomposition.find_equivalence_empty_component_run_count() == 0u);
        REQUIRE(decomposition.generated_substitution_count() == 2u);
        REQUIRE(decomposition.non_singleton_equivalence_component_count() == 2u);
        REQUIRE(decomposition.max_substitutions_per_component() == 1u);
        REQUIRE(decomposition.equivalence_coverage_per_node_per_mille() == 500u);
        REQUIRE(decomposition.substitution_density_per_node_per_mille() == 500u);
        REQUIRE(decomposition.successor_scans_per_unique_edge_per_mille() == 1000u);
        const auto baseline_equivalence_snapshot = decomposition.equivalence_metrics_snapshot();
        REQUIRE(baseline_equivalence_snapshot.find_equivalence_run_count == 1u);
        REQUIRE(baseline_equivalence_snapshot.find_equivalence_empty_component_run_count == 0u);
        REQUIRE(baseline_equivalence_snapshot.equivalence_count == 2u);
        REQUIRE(baseline_equivalence_snapshot.substitution_count == 2u);
        REQUIRE(baseline_equivalence_snapshot.generated_substitution_count == 2u);
        REQUIRE(baseline_equivalence_snapshot.non_singleton_equivalence_component_count == 2u);
        REQUIRE(baseline_equivalence_snapshot.max_substitutions_per_component == 1u);
        REQUIRE(baseline_equivalence_snapshot.equivalence_coverage_per_node_per_mille == 500u);
        REQUIRE(baseline_equivalence_snapshot.substitution_density_per_node_per_mille == 500u);
        const auto substitutions = decomposition.substitutions();
        REQUIRE(substitutions.size() == 2u);
        REQUIRE(substitutions[0].first == 2u);
        REQUIRE(substitutions[0].second == 1u);
        REQUIRE(substitutions[1].first == 4u);
        REQUIRE(substitutions[1].second == 3u);
        decomposition.emit_substitutions();
        REQUIRE(decomposition.node_count() == 4u);
        REQUIRE(decomposition.component_count() == 2u);
        REQUIRE(decomposition.singleton_component_count() == 0u);
        REQUIRE(decomposition.non_singleton_component_count() == 2u);
        REQUIRE(decomposition.max_component_size() == 2u);
        REQUIRE(decomposition.equivalence_count() == 2u);
        REQUIRE(decomposition.substitution_count() == 2u);
        REQUIRE(decomposition_substitutor.pending_rewrite_count() == 2u);
        REQUIRE(decomposition.emit_run_count() == 1u);
        REQUIRE(decomposition.emit_skip_count() == 0u);
        REQUIRE(decomposition.emit_without_substitutor_count() == 0u);
        REQUIRE(decomposition.last_emitted_substitution_count() == 2u);
        REQUIRE(decomposition.total_emitted_substitution_count() == 2u);
        const auto baseline_emit_snapshot = decomposition.emit_metrics_snapshot();
        REQUIRE(baseline_emit_snapshot.emit_run_count == 1u);
        REQUIRE(baseline_emit_snapshot.emit_skip_count == 0u);
        REQUIRE(baseline_emit_snapshot.emit_without_substitutor_count == 0u);
        REQUIRE(baseline_emit_snapshot.last_emitted_substitution_count == 2u);
        REQUIRE(baseline_emit_snapshot.total_emitted_substitution_count == 2u);
        REQUIRE(baseline_emit_snapshot.substitutions_emitted);
        const auto baseline_consistency_after_emit = decomposition.consistency_metrics_snapshot();
        REQUIRE(baseline_consistency_after_emit.implication_accounting_consistent);
        REQUIRE(baseline_consistency_after_emit.component_accounting_consistent);
        REQUIRE(baseline_consistency_after_emit.substitution_accounting_consistent);
        REQUIRE(baseline_consistency_after_emit.emit_accounting_consistent);
        REQUIRE(baseline_consistency_after_emit.reset_accounting_consistent);
        REQUIRE(baseline_consistency_after_emit.overall_consistent);
        REQUIRE(decomposition.telemetry_consistent());
        decomposition.emit_substitutions();
        REQUIRE(decomposition_substitutor.pending_rewrite_count() == 2u);
        REQUIRE(decomposition.emit_run_count() == 1u);
        REQUIRE(decomposition.emit_skip_count() == 1u);
        REQUIRE(decomposition.emit_without_substitutor_count() == 0u);
        REQUIRE(decomposition.last_emitted_substitution_count() == 2u);
        REQUIRE(decomposition.total_emitted_substitution_count() == 2u);
        const auto baseline_emit_snapshot_after_skip = decomposition.emit_metrics_snapshot();
        REQUIRE(baseline_emit_snapshot_after_skip.emit_run_count == 1u);
        REQUIRE(baseline_emit_snapshot_after_skip.emit_skip_count == 1u);
        REQUIRE(baseline_emit_snapshot_after_skip.emit_without_substitutor_count == 0u);
        REQUIRE(baseline_emit_snapshot_after_skip.last_emitted_substitution_count == 2u);
        REQUIRE(baseline_emit_snapshot_after_skip.total_emitted_substitution_count == 2u);
        REQUIRE(baseline_emit_snapshot_after_skip.substitutions_emitted);

        // Different insertion order should still produce deterministic substitution ordering.
        engine::decomposition decomposition_reordered;
        decomposition_reordered.add_implication(4u, 3u);
        decomposition_reordered.add_implication(2u, 3u);
        decomposition_reordered.add_implication(2u, 1u);
        decomposition_reordered.add_implication(1u, 2u);
        decomposition_reordered.add_implication(3u, 4u);
        decomposition_reordered.run_scc();
        decomposition_reordered.find_equivalences();
        const auto reordered_substitutions = decomposition_reordered.substitutions();
        REQUIRE(reordered_substitutions.size() == 2u);
        REQUIRE(reordered_substitutions[0].first == 2u);
        REQUIRE(reordered_substitutions[0].second == 1u);
        REQUIRE(reordered_substitutions[1].first == 4u);
        REQUIRE(reordered_substitutions[1].second == 3u);

        // Larger mixed SCC graph should keep stable representatives and ordered substitutions.
        engine::decomposition decomposition_mixed;
        REQUIRE_FALSE(decomposition_mixed.has_substitutor());
        decomposition_mixed.add_implication(12u, 10u);
        decomposition_mixed.add_implication(11u, 12u);
        decomposition_mixed.add_implication(10u, 11u);
        decomposition_mixed.add_implication(8u, 7u);
        decomposition_mixed.add_implication(7u, 8u);
        decomposition_mixed.add_implication(8u, 9u);
        REQUIRE(decomposition_mixed.edge_density_per_node_per_mille() == 1000u);
        decomposition_mixed.run_scc();
        REQUIRE(decomposition_mixed.scc_run_count() == 1u);
        REQUIRE(decomposition_mixed.tarjan_visit_count() == 6u);
        REQUIRE(decomposition_mixed.max_tarjan_stack_depth() == 3u);
        REQUIRE(decomposition_mixed.successor_scan_count() == 6u);
        REQUIRE(decomposition_mixed.tree_edge_relaxation_count() == 4u);
        REQUIRE(decomposition_mixed.back_edge_relaxation_count() == 2u);
        REQUIRE(decomposition_mixed.root_component_extraction_count() == 3u);
        REQUIRE(decomposition_mixed.canonicalized_successor_list_count() == 5u);
        REQUIRE(decomposition_mixed.canonicalized_successor_edge_count() == 6u);
        REQUIRE(decomposition_mixed.average_component_size_floor() == 2u);
        decomposition_mixed.find_equivalences();
        REQUIRE(decomposition_mixed.find_equivalence_run_count() == 1u);
        REQUIRE(decomposition_mixed.generated_substitution_count() == 3u);
        REQUIRE(decomposition_mixed.non_singleton_equivalence_component_count() == 2u);
        REQUIRE(decomposition_mixed.max_substitutions_per_component() == 2u);
        REQUIRE(decomposition_mixed.equivalence_coverage_per_node_per_mille() == 500u);
        REQUIRE(decomposition_mixed.substitution_density_per_node_per_mille() == 500u);
        REQUIRE(decomposition_mixed.successor_scans_per_unique_edge_per_mille() == 1000u);
        const auto mixed_equivalence_snapshot = decomposition_mixed.equivalence_metrics_snapshot();
        REQUIRE(mixed_equivalence_snapshot.equivalence_count == 3u);
        REQUIRE(mixed_equivalence_snapshot.substitution_count == 3u);
        REQUIRE(mixed_equivalence_snapshot.generated_substitution_count == 3u);
        REQUIRE(mixed_equivalence_snapshot.non_singleton_equivalence_component_count == 2u);
        REQUIRE(mixed_equivalence_snapshot.max_substitutions_per_component == 2u);
        REQUIRE(decomposition_mixed.telemetry_consistent());
        const auto mixed_substitutions = decomposition_mixed.substitutions();
        REQUIRE(decomposition_mixed.singleton_component_count() == 1u);
        REQUIRE(decomposition_mixed.non_singleton_component_count() == 2u);
        REQUIRE(mixed_substitutions.size() == 3u);
        REQUIRE(mixed_substitutions[0].first == 8u);
        REQUIRE(mixed_substitutions[0].second == 7u);
        REQUIRE(mixed_substitutions[1].first == 11u);
        REQUIRE(mixed_substitutions[1].second == 10u);
        REQUIRE(mixed_substitutions[2].first == 12u);
        REQUIRE(mixed_substitutions[2].second == 10u);

        // Reordered edge insertion must preserve the exact emitted substitution order.
        engine::decomposition decomposition_mixed_reordered;
        decomposition_mixed_reordered.add_implication(8u, 9u);
        decomposition_mixed_reordered.add_implication(7u, 8u);
        decomposition_mixed_reordered.add_implication(8u, 7u);
        decomposition_mixed_reordered.add_implication(10u, 11u);
        decomposition_mixed_reordered.add_implication(11u, 12u);
        decomposition_mixed_reordered.add_implication(12u, 10u);
        decomposition_mixed_reordered.run_scc();
        decomposition_mixed_reordered.find_equivalences();
        const auto mixed_reordered_substitutions = decomposition_mixed_reordered.substitutions();
        REQUIRE(mixed_reordered_substitutions.size() == mixed_substitutions.size());
        for (std::size_t index = 0; index < mixed_substitutions.size(); ++index)
        {
            REQUIRE(mixed_reordered_substitutions[index].first == mixed_substitutions[index].first);
            REQUIRE(mixed_reordered_substitutions[index].second == mixed_substitutions[index].second);
        }

        // Disconnected SCC islands should emit globally sorted substitutions.
        engine::decomposition decomposition_islands;
        decomposition_islands.add_implication(42u, 40u);
        decomposition_islands.add_implication(41u, 42u);
        decomposition_islands.add_implication(40u, 41u);
        decomposition_islands.add_implication(31u, 30u);
        decomposition_islands.add_implication(30u, 31u);
        decomposition_islands.add_implication(51u, 50u);
        decomposition_islands.add_implication(50u, 51u);
        decomposition_islands.run_scc();
        decomposition_islands.find_equivalences();
        const auto island_substitutions = decomposition_islands.substitutions();
        REQUIRE(decomposition_islands.max_component_size() == 3u);
        REQUIRE(island_substitutions.size() == 4u);
        REQUIRE(island_substitutions[0].first == 31u);
        REQUIRE(island_substitutions[0].second == 30u);
        REQUIRE(island_substitutions[1].first == 41u);
        REQUIRE(island_substitutions[1].second == 40u);
        REQUIRE(island_substitutions[2].first == 42u);
        REQUIRE(island_substitutions[2].second == 40u);
        REQUIRE(island_substitutions[3].first == 51u);
        REQUIRE(island_substitutions[3].second == 50u);

        // Duplicate implications should not affect equivalence extraction determinism.
        engine::decomposition decomposition_with_duplicates;
        decomposition_with_duplicates.add_implication(2u, 1u);
        decomposition_with_duplicates.add_implication(2u, 1u);
        decomposition_with_duplicates.add_implication(1u, 2u);
        decomposition_with_duplicates.add_implication(1u, 2u);
        decomposition_with_duplicates.add_implication(4u, 3u);
        decomposition_with_duplicates.add_implication(4u, 3u);
        decomposition_with_duplicates.add_implication(3u, 4u);
        decomposition_with_duplicates.add_implication(3u, 4u);
        decomposition_with_duplicates.add_implication(0u, 4u);
        decomposition_with_duplicates.add_implication(2u, 0u);
        decomposition_with_duplicates.run_scc();
        REQUIRE(decomposition_with_duplicates.scc_run_count() == 1u);
        REQUIRE(decomposition_with_duplicates.tarjan_visit_count() == 4u);
        REQUIRE(decomposition_with_duplicates.successor_scan_count() == 4u);
        REQUIRE(decomposition_with_duplicates.tree_edge_relaxation_count() == 2u);
        REQUIRE(decomposition_with_duplicates.back_edge_relaxation_count() == 2u);
        REQUIRE(decomposition_with_duplicates.root_component_extraction_count() == 2u);
        decomposition_with_duplicates.find_equivalences();
        REQUIRE(decomposition_with_duplicates.find_equivalence_run_count() == 1u);
        REQUIRE(decomposition_with_duplicates.generated_substitution_count() == 2u);
        REQUIRE(decomposition_with_duplicates.non_singleton_equivalence_component_count() == 2u);
        REQUIRE(decomposition_with_duplicates.max_substitutions_per_component() == 1u);
        const auto duplicate_substitutions = decomposition_with_duplicates.substitutions();
        REQUIRE(decomposition_with_duplicates.has_implication(1u, 2u));
        REQUIRE(decomposition_with_duplicates.has_implication(2u, 1u));
        REQUIRE_FALSE(decomposition_with_duplicates.has_implication(5u, 6u));
        REQUIRE(decomposition_with_duplicates.outgoing_implication_count(1u) == 1u);
        REQUIRE(decomposition_with_duplicates.outgoing_implication_count(2u) == 1u);
        REQUIRE(decomposition_with_duplicates.outgoing_implication_count(4u) == 1u);
        REQUIRE(decomposition_with_duplicates.outgoing_implication_count(3u) == 1u);
        REQUIRE(decomposition_with_duplicates.unique_implication_edge_count() == 4u);
        REQUIRE(decomposition_with_duplicates.implication_attempt_count() == 10u);
        REQUIRE(decomposition_with_duplicates.rejected_zero_implication_count() == 2u);
        REQUIRE(decomposition_with_duplicates.accepted_implication_count() == 4u);
        REQUIRE(decomposition_with_duplicates.edge_density_per_node_per_mille() == 1000u);
        REQUIRE(decomposition_with_duplicates.average_outgoing_implication_per_node_floor() == 1u);
        REQUIRE(decomposition_with_duplicates.dropped_duplicate_edge_count() == 4u);
        REQUIRE(duplicate_substitutions.size() == 2u);
        REQUIRE(duplicate_substitutions[0].first == 2u);
        REQUIRE(duplicate_substitutions[0].second == 1u);
        REQUIRE(duplicate_substitutions[1].first == 4u);
        REQUIRE(duplicate_substitutions[1].second == 3u);
        decomposition_with_duplicates.emit_substitutions();
        REQUIRE(decomposition_with_duplicates.emit_run_count() == 1u);
        REQUIRE(decomposition_with_duplicates.emit_skip_count() == 0u);
        REQUIRE(decomposition_with_duplicates.emit_without_substitutor_count() == 1u);
        REQUIRE(decomposition_with_duplicates.last_emitted_substitution_count() == 2u);
        REQUIRE(decomposition_with_duplicates.total_emitted_substitution_count() == 2u);
        const auto duplicate_emit_snapshot = decomposition_with_duplicates.emit_metrics_snapshot();
        REQUIRE(duplicate_emit_snapshot.emit_run_count == 1u);
        REQUIRE(duplicate_emit_snapshot.emit_skip_count == 0u);
        REQUIRE(duplicate_emit_snapshot.emit_without_substitutor_count == 1u);
        REQUIRE(duplicate_emit_snapshot.last_emitted_substitution_count == 2u);
        REQUIRE(duplicate_emit_snapshot.total_emitted_substitution_count == 2u);
        REQUIRE(duplicate_emit_snapshot.substitutions_emitted);
        REQUIRE(decomposition_with_duplicates.telemetry_consistent());
        decomposition_with_duplicates.emit_substitutions();
        REQUIRE(decomposition_with_duplicates.emit_run_count() == 1u);
        REQUIRE(decomposition_with_duplicates.emit_skip_count() == 1u);
        REQUIRE(decomposition_with_duplicates.emit_without_substitutor_count() == 1u);
        const auto duplicate_emit_snapshot_after_skip = decomposition_with_duplicates.emit_metrics_snapshot();
        REQUIRE(duplicate_emit_snapshot_after_skip.emit_run_count == 1u);
        REQUIRE(duplicate_emit_snapshot_after_skip.emit_skip_count == 1u);
        REQUIRE(duplicate_emit_snapshot_after_skip.emit_without_substitutor_count == 1u);
        REQUIRE(duplicate_emit_snapshot_after_skip.last_emitted_substitution_count == 2u);
        REQUIRE(duplicate_emit_snapshot_after_skip.total_emitted_substitution_count == 2u);
        REQUIRE(duplicate_emit_snapshot_after_skip.substitutions_emitted);
        decomposition_with_duplicates.clear_graph();
        const auto duplicate_clear_reset_snapshot = decomposition_with_duplicates.reset_metrics_snapshot();
        const auto duplicate_clear_reset_epoch_snapshot = decomposition_with_duplicates.reset_epoch_metrics_snapshot();
        REQUIRE(duplicate_clear_reset_snapshot.reset_graph_invocation_count == 1u);
        REQUIRE(duplicate_clear_reset_snapshot.reset_run_invocation_count == 1u);
        REQUIRE(duplicate_clear_reset_snapshot.reset_emit_invocation_count == 1u);
        REQUIRE(duplicate_clear_reset_snapshot.reset_telemetry_invocation_count == 1u);
        REQUIRE(duplicate_clear_reset_snapshot.clear_graph_invocation_count == 1u);
        REQUIRE(duplicate_clear_reset_snapshot.total_reset_invocation_count == 5u);
        REQUIRE(duplicate_clear_reset_epoch_snapshot.reset_timeline_tick == 5u);
        REQUIRE(duplicate_clear_reset_epoch_snapshot.last_clear_graph_tick == 1u);
        REQUIRE(duplicate_clear_reset_epoch_snapshot.last_reset_telemetry_tick == 2u);
        REQUIRE(duplicate_clear_reset_epoch_snapshot.last_reset_graph_tick == 3u);
        REQUIRE(duplicate_clear_reset_epoch_snapshot.last_reset_run_tick == 4u);
        REQUIRE(duplicate_clear_reset_epoch_snapshot.last_reset_emit_tick == 5u);
        REQUIRE(decomposition_with_duplicates.node_count() == 0u);
        REQUIRE(decomposition_with_duplicates.substitution_count() == 0u);
        REQUIRE(decomposition_with_duplicates.unique_implication_edge_count() == 0u);
        REQUIRE(decomposition_with_duplicates.implication_attempt_count() == 0u);
        REQUIRE(decomposition_with_duplicates.rejected_zero_implication_count() == 0u);
        REQUIRE(decomposition_with_duplicates.dropped_duplicate_edge_count() == 0u);
        REQUIRE(decomposition_with_duplicates.scc_run_count() == 0u);
        REQUIRE(decomposition_with_duplicates.tarjan_visit_count() == 0u);
        REQUIRE(decomposition_with_duplicates.max_tarjan_stack_depth() == 0u);
        REQUIRE(decomposition_with_duplicates.successor_scan_count() == 0u);
        REQUIRE(decomposition_with_duplicates.tree_edge_relaxation_count() == 0u);
        REQUIRE(decomposition_with_duplicates.back_edge_relaxation_count() == 0u);
        REQUIRE(decomposition_with_duplicates.root_component_extraction_count() == 0u);
        REQUIRE(decomposition_with_duplicates.canonicalized_successor_list_count() == 0u);
        REQUIRE(decomposition_with_duplicates.canonicalized_successor_edge_count() == 0u);
        REQUIRE(decomposition_with_duplicates.scc_empty_run_count() == 0u);
        REQUIRE(decomposition_with_duplicates.find_equivalence_run_count() == 0u);
        REQUIRE(decomposition_with_duplicates.find_equivalence_empty_component_run_count() == 0u);
        REQUIRE(decomposition_with_duplicates.generated_substitution_count() == 0u);
        REQUIRE(decomposition_with_duplicates.non_singleton_equivalence_component_count() == 0u);
        REQUIRE(decomposition_with_duplicates.max_substitutions_per_component() == 0u);
        REQUIRE(decomposition_with_duplicates.emit_run_count() == 0u);
        REQUIRE(decomposition_with_duplicates.emit_skip_count() == 0u);
        REQUIRE(decomposition_with_duplicates.emit_without_substitutor_count() == 0u);
        REQUIRE(decomposition_with_duplicates.last_emitted_substitution_count() == 0u);
        REQUIRE(decomposition_with_duplicates.total_emitted_substitution_count() == 0u);
        REQUIRE(decomposition_with_duplicates.singleton_component_count() == 0u);
        REQUIRE(decomposition_with_duplicates.non_singleton_component_count() == 0u);
        REQUIRE(decomposition_with_duplicates.max_component_size() == 0u);
        REQUIRE(decomposition_with_duplicates.average_outgoing_implication_per_node_floor() == 0u);
        REQUIRE(decomposition_with_duplicates.average_component_size_floor() == 0u);
        REQUIRE(decomposition_with_duplicates.equivalence_coverage_per_node_per_mille() == 0u);
        REQUIRE(decomposition_with_duplicates.substitution_density_per_node_per_mille() == 0u);
        REQUIRE(decomposition_with_duplicates.successor_scans_per_unique_edge_per_mille() == 0u);
        REQUIRE_FALSE(decomposition_with_duplicates.has_implication(1u, 2u));
        REQUIRE(decomposition_with_duplicates.outgoing_implication_count(1u) == 0u);
        decomposition_with_duplicates.add_implication(6u, 5u);
        decomposition_with_duplicates.add_implication(6u, 5u);
        REQUIRE(decomposition_with_duplicates.unique_implication_edge_count() == 1u);
        REQUIRE(decomposition_with_duplicates.dropped_duplicate_edge_count() == 1u);
        REQUIRE(decomposition_with_duplicates.outgoing_implication_count(6u) == 1u);
        REQUIRE(decomposition_with_duplicates.has_implication(6u, 5u));

        engine::decomposition decomposition_resets;
        decomposition_resets.add_implication(1u, 2u);
        decomposition_resets.add_implication(2u, 1u);
        decomposition_resets.add_implication(2u, 1u);
        decomposition_resets.add_implication(0u, 5u);
        decomposition_resets.run_scc();
        decomposition_resets.find_equivalences();
        decomposition_resets.emit_substitutions();
        REQUIRE(decomposition_resets.implication_attempt_count() == 4u);
        REQUIRE(decomposition_resets.rejected_zero_implication_count() == 1u);
        REQUIRE(decomposition_resets.dropped_duplicate_edge_count() == 1u);
        REQUIRE(decomposition_resets.emit_run_count() == 1u);
        REQUIRE(decomposition_resets.find_equivalence_run_count() == 1u);
        REQUIRE(decomposition_resets.scc_run_count() == 1u);
        REQUIRE(decomposition_resets.component_count() == 1u);
        REQUIRE(decomposition_resets.substitution_count() == 1u);
        REQUIRE(decomposition_resets.telemetry_consistent());
        auto resets_snapshot = decomposition_resets.reset_metrics_snapshot();
        auto resets_epoch_snapshot = decomposition_resets.reset_epoch_metrics_snapshot();
        REQUIRE(resets_snapshot.reset_graph_invocation_count == 0u);
        REQUIRE(resets_snapshot.reset_run_invocation_count == 0u);
        REQUIRE(resets_snapshot.reset_emit_invocation_count == 0u);
        REQUIRE(resets_snapshot.reset_telemetry_invocation_count == 0u);
        REQUIRE(resets_snapshot.clear_graph_invocation_count == 0u);
        REQUIRE(resets_snapshot.total_reset_invocation_count == 0u);
        REQUIRE(resets_epoch_snapshot.reset_timeline_tick == 0u);
        REQUIRE(resets_epoch_snapshot.last_reset_graph_tick == 0u);
        REQUIRE(resets_epoch_snapshot.last_reset_run_tick == 0u);
        REQUIRE(resets_epoch_snapshot.last_reset_emit_tick == 0u);
        REQUIRE(resets_epoch_snapshot.last_reset_telemetry_tick == 0u);
        REQUIRE(resets_epoch_snapshot.last_clear_graph_tick == 0u);

        const auto resets_before_emit_reset = resets_snapshot;
        decomposition_resets.reset_emit_metrics();
        REQUIRE(decomposition_resets.emit_run_count() == 0u);
        REQUIRE(decomposition_resets.emit_skip_count() == 0u);
        REQUIRE(decomposition_resets.emit_without_substitutor_count() == 0u);
        REQUIRE(decomposition_resets.total_emitted_substitution_count() == 0u);
        REQUIRE(decomposition_resets.last_emitted_substitution_count() == 0u);
        REQUIRE_FALSE(decomposition_resets.substitutions_emitted());
        REQUIRE(decomposition_resets.find_equivalence_run_count() == 1u);
        REQUIRE(decomposition_resets.scc_run_count() == 1u);
        REQUIRE(decomposition_resets.implication_attempt_count() == 4u);
        resets_snapshot = decomposition_resets.reset_metrics_snapshot();
        REQUIRE(resets_snapshot.reset_graph_invocation_count == 0u);
        REQUIRE(resets_snapshot.reset_run_invocation_count == 0u);
        REQUIRE(resets_snapshot.reset_emit_invocation_count == 1u);
        REQUIRE(resets_snapshot.reset_telemetry_invocation_count == 0u);
        REQUIRE(resets_snapshot.clear_graph_invocation_count == 0u);
        REQUIRE(resets_snapshot.total_reset_invocation_count == 1u);
        REQUIRE(engine::decomposition::reset_metrics_monotonic(resets_before_emit_reset, resets_snapshot));
        const auto resets_emit_delta =
            engine::decomposition::reset_metrics_delta_between(resets_before_emit_reset, resets_snapshot);
        REQUIRE(resets_emit_delta.reset_graph_invocation_count == 0u);
        REQUIRE(resets_emit_delta.reset_run_invocation_count == 0u);
        REQUIRE(resets_emit_delta.reset_emit_invocation_count == 1u);
        REQUIRE(resets_emit_delta.reset_telemetry_invocation_count == 0u);
        REQUIRE(resets_emit_delta.clear_graph_invocation_count == 0u);
        REQUIRE(resets_emit_delta.total_reset_invocation_count == 1u);
        resets_epoch_snapshot = decomposition_resets.reset_epoch_metrics_snapshot();
        REQUIRE(resets_epoch_snapshot.reset_timeline_tick == 1u);
        REQUIRE(resets_epoch_snapshot.last_reset_graph_tick == 0u);
        REQUIRE(resets_epoch_snapshot.last_reset_run_tick == 0u);
        REQUIRE(resets_epoch_snapshot.last_reset_emit_tick == 1u);
        REQUIRE(resets_epoch_snapshot.last_reset_telemetry_tick == 0u);
        REQUIRE(resets_epoch_snapshot.last_clear_graph_tick == 0u);

        decomposition_resets.emit_substitutions();
        REQUIRE(decomposition_resets.emit_run_count() == 1u);
        REQUIRE(decomposition_resets.emit_without_substitutor_count() == 1u);
        REQUIRE(decomposition_resets.last_emitted_substitution_count() == 1u);

        const auto resets_before_run_reset = resets_snapshot;
        decomposition_resets.reset_run_metrics();
        REQUIRE(decomposition_resets.scc_run_count() == 0u);
        REQUIRE(decomposition_resets.scc_empty_run_count() == 0u);
        REQUIRE(decomposition_resets.find_equivalence_run_count() == 0u);
        REQUIRE(decomposition_resets.find_equivalence_empty_component_run_count() == 0u);
        REQUIRE(decomposition_resets.generated_substitution_count() == 0u);
        REQUIRE(decomposition_resets.component_count() == 0u);
        REQUIRE(decomposition_resets.equivalence_count() == 0u);
        REQUIRE(decomposition_resets.substitution_count() == 0u);
        REQUIRE(decomposition_resets.successor_scan_count() == 0u);
        REQUIRE(decomposition_resets.max_component_size() == 0u);
        REQUIRE(decomposition_resets.canonicalized_successor_list_count() == 0u);
        REQUIRE(decomposition_resets.canonicalized_successor_edge_count() == 0u);
        REQUIRE(decomposition_resets.implication_attempt_count() == 4u);
        REQUIRE(decomposition_resets.unique_implication_edge_count() == 2u);
        REQUIRE(decomposition_resets.node_count() == 2u);
        resets_snapshot = decomposition_resets.reset_metrics_snapshot();
        REQUIRE(resets_snapshot.reset_graph_invocation_count == 0u);
        REQUIRE(resets_snapshot.reset_run_invocation_count == 1u);
        REQUIRE(resets_snapshot.reset_emit_invocation_count == 1u);
        REQUIRE(resets_snapshot.reset_telemetry_invocation_count == 0u);
        REQUIRE(resets_snapshot.clear_graph_invocation_count == 0u);
        REQUIRE(resets_snapshot.total_reset_invocation_count == 2u);
        REQUIRE(engine::decomposition::reset_metrics_monotonic(resets_before_run_reset, resets_snapshot));
        const auto resets_run_delta =
            engine::decomposition::reset_metrics_delta_between(resets_before_run_reset, resets_snapshot);
        REQUIRE(resets_run_delta.reset_graph_invocation_count == 0u);
        REQUIRE(resets_run_delta.reset_run_invocation_count == 1u);
        REQUIRE(resets_run_delta.reset_emit_invocation_count == 0u);
        REQUIRE(resets_run_delta.reset_telemetry_invocation_count == 0u);
        REQUIRE(resets_run_delta.clear_graph_invocation_count == 0u);
        REQUIRE(resets_run_delta.total_reset_invocation_count == 1u);
        resets_epoch_snapshot = decomposition_resets.reset_epoch_metrics_snapshot();
        REQUIRE(resets_epoch_snapshot.reset_timeline_tick == 2u);
        REQUIRE(resets_epoch_snapshot.last_reset_graph_tick == 0u);
        REQUIRE(resets_epoch_snapshot.last_reset_run_tick == 2u);
        REQUIRE(resets_epoch_snapshot.last_reset_emit_tick == 1u);
        REQUIRE(resets_epoch_snapshot.last_reset_telemetry_tick == 0u);
        REQUIRE(resets_epoch_snapshot.last_clear_graph_tick == 0u);

        const auto resets_before_telemetry_reset = resets_snapshot;
        decomposition_resets.reset_telemetry_metrics();
        REQUIRE(decomposition_resets.implication_attempt_count() == 0u);
        REQUIRE(decomposition_resets.rejected_zero_implication_count() == 0u);
        REQUIRE(decomposition_resets.dropped_duplicate_edge_count() == 0u);
        REQUIRE(decomposition_resets.scc_run_count() == 0u);
        REQUIRE(decomposition_resets.find_equivalence_run_count() == 0u);
        REQUIRE(decomposition_resets.emit_run_count() == 0u);
        REQUIRE(decomposition_resets.component_count() == 0u);
        REQUIRE(decomposition_resets.substitution_count() == 0u);
        REQUIRE(decomposition_resets.node_count() == 2u);
        REQUIRE(decomposition_resets.unique_implication_edge_count() == 2u);
        REQUIRE(decomposition_resets.telemetry_consistent());
        const auto reset_telemetry_graph_snapshot = decomposition_resets.graph_metrics_snapshot();
        REQUIRE(reset_telemetry_graph_snapshot.node_count == 2u);
        REQUIRE(reset_telemetry_graph_snapshot.unique_implication_edge_count == 2u);
        REQUIRE(reset_telemetry_graph_snapshot.implication_attempt_count == 0u);
        resets_snapshot = decomposition_resets.reset_metrics_snapshot();
        REQUIRE(resets_snapshot.reset_graph_invocation_count == 1u);
        REQUIRE(resets_snapshot.reset_run_invocation_count == 2u);
        REQUIRE(resets_snapshot.reset_emit_invocation_count == 2u);
        REQUIRE(resets_snapshot.reset_telemetry_invocation_count == 1u);
        REQUIRE(resets_snapshot.clear_graph_invocation_count == 0u);
        REQUIRE(resets_snapshot.total_reset_invocation_count == 6u);
        REQUIRE(engine::decomposition::reset_metrics_monotonic(resets_before_telemetry_reset, resets_snapshot));
        const auto resets_telemetry_delta =
            engine::decomposition::reset_metrics_delta_between(resets_before_telemetry_reset, resets_snapshot);
        REQUIRE(resets_telemetry_delta.reset_graph_invocation_count == 1u);
        REQUIRE(resets_telemetry_delta.reset_run_invocation_count == 1u);
        REQUIRE(resets_telemetry_delta.reset_emit_invocation_count == 1u);
        REQUIRE(resets_telemetry_delta.reset_telemetry_invocation_count == 1u);
        REQUIRE(resets_telemetry_delta.clear_graph_invocation_count == 0u);
        REQUIRE(resets_telemetry_delta.total_reset_invocation_count == 4u);
        resets_epoch_snapshot = decomposition_resets.reset_epoch_metrics_snapshot();
        REQUIRE(resets_epoch_snapshot.reset_timeline_tick == 6u);
        REQUIRE(resets_epoch_snapshot.last_reset_graph_tick == 4u);
        REQUIRE(resets_epoch_snapshot.last_reset_run_tick == 5u);
        REQUIRE(resets_epoch_snapshot.last_reset_emit_tick == 6u);
        REQUIRE(resets_epoch_snapshot.last_reset_telemetry_tick == 3u);
        REQUIRE(resets_epoch_snapshot.last_clear_graph_tick == 0u);

        decomposition_resets.run_scc();
        decomposition_resets.find_equivalences();
        REQUIRE(decomposition_resets.scc_run_count() == 1u);
        REQUIRE(decomposition_resets.find_equivalence_run_count() == 1u);
        REQUIRE(decomposition_resets.substitution_count() == 1u);
        REQUIRE(decomposition_resets.telemetry_consistent());

        decomposition_resets.reset_graph_metrics();
        REQUIRE(decomposition_resets.implication_attempt_count() == 0u);
        REQUIRE(decomposition_resets.rejected_zero_implication_count() == 0u);
        REQUIRE(decomposition_resets.dropped_duplicate_edge_count() == 0u);
        REQUIRE(decomposition_resets.unique_implication_edge_count() == 2u);
        REQUIRE(decomposition_resets.node_count() == 2u);
        REQUIRE(decomposition_resets.scc_run_count() == 1u);
        REQUIRE(decomposition_resets.find_equivalence_run_count() == 1u);
        REQUIRE(decomposition_resets.telemetry_consistent());
        resets_snapshot = decomposition_resets.reset_metrics_snapshot();
        const auto resets_epoch_after_graph_reset = decomposition_resets.reset_epoch_metrics_snapshot();
        REQUIRE(resets_snapshot.reset_graph_invocation_count == 2u);
        REQUIRE(resets_snapshot.reset_run_invocation_count == 2u);
        REQUIRE(resets_snapshot.reset_emit_invocation_count == 2u);
        REQUIRE(resets_snapshot.reset_telemetry_invocation_count == 1u);
        REQUIRE(resets_snapshot.clear_graph_invocation_count == 0u);
        REQUIRE(resets_snapshot.total_reset_invocation_count == 7u);
        REQUIRE(resets_epoch_after_graph_reset.reset_timeline_tick == 7u);
        REQUIRE(resets_epoch_after_graph_reset.last_reset_graph_tick == 7u);
        REQUIRE(resets_epoch_after_graph_reset.last_reset_run_tick == 5u);
        REQUIRE(resets_epoch_after_graph_reset.last_reset_emit_tick == 6u);
        REQUIRE(resets_epoch_after_graph_reset.last_reset_telemetry_tick == 3u);
        REQUIRE(resets_epoch_after_graph_reset.last_clear_graph_tick == 0u);

        engine::decomposition decomposition_empty;
        REQUIRE_FALSE(decomposition_empty.has_substitutor());
        decomposition_empty.run_scc();
        REQUIRE(decomposition_empty.scc_run_count() == 1u);
        REQUIRE(decomposition_empty.scc_empty_run_count() == 1u);
        REQUIRE(decomposition_empty.component_count() == 0u);
        REQUIRE(decomposition_empty.canonicalized_successor_list_count() == 0u);
        REQUIRE(decomposition_empty.canonicalized_successor_edge_count() == 0u);
        decomposition_empty.find_equivalences();
        REQUIRE(decomposition_empty.find_equivalence_run_count() == 1u);
        REQUIRE(decomposition_empty.find_equivalence_empty_component_run_count() == 1u);
        REQUIRE(decomposition_empty.generated_substitution_count() == 0u);
        REQUIRE(decomposition_empty.non_singleton_equivalence_component_count() == 0u);
        REQUIRE(decomposition_empty.max_substitutions_per_component() == 0u);
        REQUIRE(decomposition_empty.edge_density_per_node_per_mille() == 0u);
        const auto empty_graph_snapshot = decomposition_empty.graph_metrics_snapshot();
        REQUIRE(empty_graph_snapshot.node_count == 0u);
        REQUIRE(empty_graph_snapshot.unique_implication_edge_count == 0u);
        REQUIRE(empty_graph_snapshot.implication_attempt_count == 0u);
        REQUIRE(empty_graph_snapshot.rejected_zero_implication_count == 0u);
        REQUIRE(empty_graph_snapshot.accepted_implication_count == 0u);
        REQUIRE(empty_graph_snapshot.dropped_duplicate_edge_count == 0u);
        REQUIRE(empty_graph_snapshot.average_outgoing_implication_per_node_floor == 0u);
        REQUIRE(empty_graph_snapshot.edge_density_per_node_per_mille == 0u);
        REQUIRE_FALSE(empty_graph_snapshot.has_substitutor);
        const auto empty_scc_snapshot = decomposition_empty.scc_metrics_snapshot();
        REQUIRE(empty_scc_snapshot.scc_run_count == 1u);
        REQUIRE(empty_scc_snapshot.scc_empty_run_count == 1u);
        REQUIRE(empty_scc_snapshot.component_count == 0u);
        REQUIRE(empty_scc_snapshot.singleton_component_count == 0u);
        REQUIRE(empty_scc_snapshot.non_singleton_component_count == 0u);
        REQUIRE(empty_scc_snapshot.max_component_size == 0u);
        REQUIRE(empty_scc_snapshot.average_component_size_floor == 0u);
        REQUIRE(empty_scc_snapshot.tarjan_visit_count == 0u);
        REQUIRE(empty_scc_snapshot.max_tarjan_stack_depth == 0u);
        REQUIRE(empty_scc_snapshot.successor_scan_count == 0u);
        REQUIRE(empty_scc_snapshot.tree_edge_relaxation_count == 0u);
        REQUIRE(empty_scc_snapshot.back_edge_relaxation_count == 0u);
        REQUIRE(empty_scc_snapshot.root_component_extraction_count == 0u);
        REQUIRE(empty_scc_snapshot.canonicalized_successor_list_count == 0u);
        REQUIRE(empty_scc_snapshot.canonicalized_successor_edge_count == 0u);
        REQUIRE(empty_scc_snapshot.successor_scans_per_unique_edge_per_mille == 0u);
        const auto empty_equivalence_snapshot = decomposition_empty.equivalence_metrics_snapshot();
        REQUIRE(empty_equivalence_snapshot.find_equivalence_run_count == 1u);
        REQUIRE(empty_equivalence_snapshot.find_equivalence_empty_component_run_count == 1u);
        REQUIRE(empty_equivalence_snapshot.equivalence_count == 0u);
        REQUIRE(empty_equivalence_snapshot.substitution_count == 0u);
        REQUIRE(empty_equivalence_snapshot.generated_substitution_count == 0u);
        REQUIRE(empty_equivalence_snapshot.non_singleton_equivalence_component_count == 0u);
        REQUIRE(empty_equivalence_snapshot.max_substitutions_per_component == 0u);
        REQUIRE(empty_equivalence_snapshot.equivalence_coverage_per_node_per_mille == 0u);
        REQUIRE(empty_equivalence_snapshot.substitution_density_per_node_per_mille == 0u);
        decomposition_empty.emit_substitutions();
        REQUIRE(decomposition_empty.emit_run_count() == 1u);
        REQUIRE(decomposition_empty.emit_skip_count() == 0u);
        REQUIRE(decomposition_empty.emit_without_substitutor_count() == 1u);
        REQUIRE(decomposition_empty.last_emitted_substitution_count() == 0u);
        REQUIRE(decomposition_empty.total_emitted_substitution_count() == 0u);
        const auto empty_emit_snapshot = decomposition_empty.emit_metrics_snapshot();
        REQUIRE(empty_emit_snapshot.emit_run_count == 1u);
        REQUIRE(empty_emit_snapshot.emit_skip_count == 0u);
        REQUIRE(empty_emit_snapshot.emit_without_substitutor_count == 1u);
        REQUIRE(empty_emit_snapshot.last_emitted_substitution_count == 0u);
        REQUIRE(empty_emit_snapshot.total_emitted_substitution_count == 0u);
        REQUIRE(empty_emit_snapshot.substitutions_emitted);
        const auto empty_consistency_snapshot = decomposition_empty.consistency_metrics_snapshot();
        REQUIRE(empty_consistency_snapshot.implication_accounting_consistent);
        REQUIRE(empty_consistency_snapshot.component_accounting_consistent);
        REQUIRE(empty_consistency_snapshot.substitution_accounting_consistent);
        REQUIRE(empty_consistency_snapshot.emit_accounting_consistent);
        REQUIRE(empty_consistency_snapshot.reset_accounting_consistent);
        REQUIRE(empty_consistency_snapshot.overall_consistent);
        REQUIRE(decomposition_empty.telemetry_consistent());

        engine::probing probing;
        const literal lit {variable {4u}, false};
        probing.probe_literal(lit);
        probing.run_failed_literal_probing();
        probing.learn_hyper_binary();
        probing.record_backbone_candidate(lit);
        REQUIRE(probing.probe_count() == 1u);
        REQUIRE(probing.hyper_binary_count() == 1u);
        REQUIRE(probing.backbone_candidate_count() == 1u);

        engine::probing database_probing;
        cdcl::clause::database probing_database;
        proof_manager probing_proof_manager;
        probing_proof_manager.enable_format("drat");
        const literal unit_lit {variable {8u}, false};
        const literal implied_lit {variable {9u}, false};
        const auto unit_ref = probing_database.add_clause(std::array<literal, 1> {unit_lit}, false);
        const auto implied_ref = probing_database.add_clause(std::array<literal, 2> {unit_lit.negated(), implied_lit}, false);
        probing_proof_manager.on_add_original(unit_ref, std::array<literal, 1> {unit_lit});
        probing_proof_manager.on_add_original(implied_ref, std::array<literal, 2> {unit_lit.negated(), implied_lit});
        database_probing.attach_database(probing_database);
        database_probing.attach_proof_manager(probing_proof_manager);
        database_probing.run_failed_literal_probing();
        const auto shrunk_clause = probing_database.storage_of().literals_of(implied_ref);
        REQUIRE(shrunk_clause.size() == 1u);
        REQUIRE(shrunk_clause[0] == implied_lit);
        REQUIRE(database_probing.hyper_binary_count() == 1u);
        REQUIRE(database_probing.backbone_candidate_count() == 1u);
        REQUIRE(probing_proof_manager.last_event().kind == proof::event_kind::shrink_clause);
        REQUIRE(probing_proof_manager.last_event().literals.size() == 1u);
        REQUIRE(probing_proof_manager.last_event().literals[0] == 9);

        transitive_reducer reducer;
        cdcl::clause::database transitive_database;
        const auto implication_ab =
            transitive_database.add_clause(std::array<literal, 2> {literal {variable {1u}, true}, literal {variable {2u}, false}}, false);
        const auto implication_bc =
            transitive_database.add_clause(std::array<literal, 2> {literal {variable {2u}, true}, literal {variable {3u}, false}}, false);
        const auto implication_ac =
            transitive_database.add_clause(std::array<literal, 2> {literal {variable {1u}, true}, literal {variable {3u}, false}}, false);
        reducer.attach_database(transitive_database);
        reducer.run();
        reducer.prune_binary_edges();
        reducer.report_removed_edges();
        REQUIRE(reducer.pruned());
        REQUIRE(reducer.removed_edge_count() == 1u);
        REQUIRE(transitive_database.stats_snapshot().irredundant_count == 2u);
        REQUIRE(transitive_database.storage_of().is_alive(implication_ab));
        REQUIRE(transitive_database.storage_of().is_alive(implication_bc));
        REQUIRE_FALSE(transitive_database.storage_of().is_alive(implication_ac));

        engine::congruence congruence;
        cdcl::clause::database congruence_clause_database;
        cdcl::bank::watch_list congruence_watch_list;
        cdcl::variable_mapper congruence_mapper;
        const variable ext_a {21u};
        const variable ext_b {22u};
        const auto internal_a = congruence_mapper.ensure_external_variable(ext_a);
        const auto internal_b = congruence_mapper.ensure_external_variable(ext_b);

        const literal lit_a_pos {internal_a, false};
        const literal lit_b_neg {internal_b, true};
        const std::array<literal, 2> congruence_clause {lit_a_pos, lit_b_neg};
        const auto congruence_clause_ref = congruence_clause_database.add_clause(congruence_clause, true);

        cdcl::watch congruence_watch {lit_a_pos, congruence_clause_ref, true};
        congruence_watch.set_binary_literal(lit_b_neg);
        congruence_watch_list.watch_literal(lit_b_neg, congruence_watch);

        congruence.attach_clause_database(congruence_clause_database);
        congruence.attach_watch_list(congruence_watch_list);
        congruence.attach_variable_mapper(congruence_mapper);
        congruence.gate_extractor().find_and_gate(10u, 3u, 5u);
        congruence.gate_extractor().find_and_gate(internal_b.index(), internal_a.index(), internal_a.index());
        congruence.gate_extractor().materialize_gate_summary();
        congruence.apply_gate_constraints();
        congruence.derive_equivalences();
        REQUIRE(congruence.substitutor().pending_rewrite_count() == 1u);
        congruence.run();
        REQUIRE(congruence.gate_constraint_count() == 2u);
        REQUIRE(congruence.equivalence_count() == 1u);
        REQUIRE(congruence.run_completed());
        REQUIRE(congruence.substitutor().rewrite_completed());
        REQUIRE(congruence.substitutor().last_applied_rewrite_count() == 2u);

        const auto rewritten_literals = congruence_clause_database.storage_of().literals_of(congruence_clause_ref);
        REQUIRE(rewritten_literals.size() == 2u);
        REQUIRE(rewritten_literals[0].variable_of().index() == internal_a.index());
        REQUIRE(rewritten_literals[1].variable_of().index() == internal_a.index());

        REQUIRE(congruence_watch_list.size_of(lit_b_neg) == 0u);
        const literal lit_a_neg {internal_a, true};
        REQUIRE(congruence_watch_list.size_of(lit_a_neg) == 1u);

        const auto remapped_internal_b = congruence_mapper.to_internal_literal(literal {ext_b, false});
        REQUIRE(remapped_internal_b.variable_of().index() == internal_a.index());

        engine::instantiation instantiation;
        instantiation.collect_candidates();
        instantiation.instantiate_literal_removal();
        instantiation.run();
        REQUIRE(instantiation.candidate_count() == 1u);
        REQUIRE(instantiation.removal_count() == 1u);
        REQUIRE(instantiation.run_completed());

        engine::sweep sweep;
        sweep.build_micro_instance();
        sweep.extract_backbone();
        sweep.extract_equivalences();
        sweep.transfer_facts();
        sweep.run();
        REQUIRE(sweep.micro_instance_built());
        REQUIRE(sweep.backbone_count() == 1u);
        REQUIRE(sweep.equivalence_count() == 1u);
        REQUIRE(sweep.transferred());
        sweep.reset();
        REQUIRE_FALSE(sweep.micro_instance_built());
        REQUIRE(sweep.backbone_count() == 0u);
        REQUIRE(sweep.equivalence_count() == 0u);
        REQUIRE_FALSE(sweep.transferred());

        // removed std::cout: "engine simplify test passed\n";
    }

} // namespace
